### ISSUE TITLE
User auth

### ISSUE THREAD

**Issue by javiermortiz** [alpvyas/code-hunt#25]
Hi team! good job so far! Here are some comments about user auth:

Great job with the links in the footer!
- [ ] The splash page image is very cool although a little bit pixelated, maybe you need a higher ref image?
- [ ] You are using 2 types of fonts in your register form. Stick to 1.
- [ ] The errors could user more styling to make them fit better with the rest of the site. I think they would also look better closer to the register form.
- [ ] Many modern websites round the edges of buttons. I suggest you do the same for your logout. Also the anchor tag is wider than the button, it doesn't look like a rectangle on hover.
- [x] The navbar needs some padding on the sides. 
Good job with the demo user!

**Comment by W-the-V** [comment]
Thanks for the input! We have tried to address all of these, I am still working on the styling of the forms on the login / register page but the majority of these issues should be fixed.

**Comment by alpvyas** [comment]
Fixed the padding, thanks for bringing it up

**Comment by alpvyas** [comment]
I hope I didn't close all the issues, I thought I was closing the issue whose box I checked. Sorry if I closed it all prematurely.
